# Site settings
title: "Robin Schramm - CV"
# description: "I'm a Human-Computer Interaction researcher, working on In-Car Augmented Reality interaction. My background consists of a mix of industry projects, academic research, and teaching experience."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Robin Connor Schramm"
resume_title:                   "CV"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "robinschramm@gmx.de"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "01602988844"
resume_contact_address:         "robinschramm@gmx.de"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

# resume_header_intro: "<p>Mail: robin.schramm@mercedes-benz.com</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_publication:     true
resume_section_experience:      true
resume_section_service:         true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_mail_url:              "robinschramm@gmx.de"
  resume_github_url:            "https://github.com/SchrammR"
  # resume_twitter_url:           "http://twitter.com/SchrammResearch"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/RobinSchramm"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://scholar.google.com/citations?hl=en&user=oKu2gN8AAAAJ"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
