# Jobs
#
- position: Reviewer
  summary: >-
    <ul class="resume-item-list">
        <li><a href="https://www.sciencedirect.com/journal/international-journal-of-human-computer-studies">International Journal of Human-Computer Studies</a>: '25</li>
        <li><a href="https://iss.acm.org/">ACM ISS</a>: '25</li>
        <li><a href="https://dl.acm.org/conference/chi/">CHI</a>: '24, '25</li>
        <li><a href="https://www.auto-ui.org/">AutomotiveUI</a>: '23</li>
        <li><a href="https://www.immersivelrn.org/">iLRN</a>: '22, '23</li>
    </ul>

#
- position: Student Volunteer
  summary: >-
    <ul class="resume-item-list">
        <li><a href="https://ieeevr.org/">IEEVR</a>: '21</li>
    </ul>
